<a href="https://colab.research.google.com/github/monishvarghesejoshy/emanzon/blob/adf_publish/try.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
p=10
q=4
z=p/q
print (z)

2.5

In [ ]:
input1=int(input("enter first digit"))

match input1:
    case 1:
        print("one")
    case 2:
        print("two")
    case 3:
        print("three")
    case 4:
        print("four")
    case 5:
        print("five")
    case _ :
        print("invalid")

enter first digit8
invalid

In [ ]:
a=[1,2,3,4,5]
for i in a:
    if i%2==1:
        print(i ,"is odd")
    else:
        print(i, "is even")

1 is odd
2 is even
3 is odd
4 is even
5 is odd

In [ ]:
for i in range(2,30,1):
  for j in range(2,i):
     if (i%j) == 0:
      print(i, "is not a prime")
      break
  else:
    print(i, "is a prime")

2 is a prime
3 is a prime
4 is not a prime
5 is a prime
6 is not a prime
7 is a prime
8 is not a prime
9 is not a prime
10 is not a prime
11 is a prime
12 is not a prime
13 is a prime
14 is not a prime
15 is not a prime
16 is not a prime
17 is a prime
18 is not a prime
19 is a prime
20 is not a prime
21 is not a prime
22 is not a prime
23 is a prime
24 is not a prime
25 is not a prime
26 is not a prime
27 is not a prime
28 is not a prime
29 is a prime

In [ ]:
x=1
while x<7:

  print (x)

  x+=1

1
2
3
4
5
6

In [ ]:
def ab(x):
     if ( x <0):
        y= x*-1
     else:
       y=x
     return(y)
ab(7)

7

In [ ]:
def sum(n):
  result=0
  for i in range(1, n+1):
        result=result+i
        i=i+1
  return(result)
sum(6)

21

In [ ]:
name='Jacob'
'a' in name

True

In [ ]:
word = '''God
is Love'''
"Love" in word

True

In [ ]:
st=''' Work Hard and Work Smart'''
for c in st:
     print( c)

W
o
r
k

H
a
r
d

a
n
d

W
o
r
k

S
m
a
r
t

In [ ]:
s1="Hello "
s2=s1.strip()
s2

'Hello'

In [ ]:
s1.replace("He","ha")

'hallo '

In [ ]:
dict1={'Name': 'Monish', 'Age':41, 'Gender':'Male'}
dict1

{'Name': 'Monish', 'Age': 41, 'Gender': 'Male'}

In [ ]:
dict1.keys()

dict_keys(['Name', 'Age', 'Gender'])

In [ ]:
dict1.values()

dict_values(['Monish', 41, 'Male'])

In [ ]:
dict1.items()

dict_items([('Name', 'Monish'), ('Age', 41), ('Gender', 'Male')])

In [ ]:

dict1.items()
del dict1['Age']
dict1

{'Name': 'Monish'}

In [ ]:
dict1.clear()
dict1

{}

In [ ]:
num=int(input('Enter the number of Employees'))
count=1
employee=dict()
while count<= num:
  name=input('Enter the name')
  salary=int(input('Enter the salary'))
  employee[name]=salary
  count+=1
for name,salary in employee.items():
  print(name,salary)

Enter the number of Employees2
Enter the namejosh
Enter the salary5000
Enter the namedan
Enter the salary4000
josh 5000
dan 4000

In [ ]:
import  numpy as np
x=np.array([1,2,3])
x
type(x)
y=np.ones((2,2), dtype=np.int16)
y

array([[1, 1],
       [1, 1]], dtype=int16)

In [ ]:
x=np.arange(10,80,5)
x

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75])

In [ ]:
y=np.linspace(0,1/4,3)
y

array([0.   , 0.125, 0.25 ])

In [ ]:
i=np.random.rand(3,4)
i

array([[0.18278344, 0.60250227, 0.80104623, 0.81954957],
       [0.71552962, 0.48223105, 0.11739357, 0.99500669],
       [0.21618479, 0.52153155, 0.41855865, 0.54314768]])

In [ ]:
j=np.empty((3,4), dtype=np.int16)


j.ndim
j.size
j.shape

(3, 4)

In [ ]:
i[2:3]

array([[0.47084623, 0.57269373, 0.67461817, 0.46024784]])

In [ ]:
k=i.reshape(4,3)
k

array([[0.18278344, 0.60250227, 0.80104623],
       [0.81954957, 0.71552962, 0.48223105],
       [0.11739357, 0.99500669, 0.21618479],
       [0.52153155, 0.41855865, 0.54314768]])

In [ ]:
k[:, 2]

array([0.80104623, 0.48223105, 0.21618479, 0.54314768])

In [ ]:
import numpy as np

# Generate the random array
i = np.random.rand(3, 4)

# Pivot (transpose) the array
pivoted = i.T

print("Original Array:")
print(i)

print("\nPivoted (Transposed) Array:")
print(pivoted)

Original Array:
[[0.91449682 0.07533168 0.61218619 0.45555297]
 [0.96900941 0.92948748 0.61029198 0.69498419]
 [0.08837159 0.70074978 0.62068661 0.71833321]]

Pivoted (Transposed) Array:
[[0.91449682 0.96900941 0.08837159]
 [0.07533168 0.92948748 0.70074978]
 [0.61218619 0.61029198 0.62068661]
 [0.45555297 0.69498419 0.71833321]]

In [ ]:
x=np.array([1,2,3])
y=[8,9,0]

In [ ]:
a=x
b=y
a[2]=1

In [ ]:
b[2]=6
y

[8, 9, 6]

In [ ]:
a[1]=0
x

array([1, 0, 1])

In [ ]:
import pandas as py
s=py.Series(x)
s

0    1
1    0
2    1
dtype: int64

In [ ]:
l=[[1,2],[3,4],[5,6],[7,8]]
df1=py.DataFrame(l)
df1

   0  1
0  1  2
1  3  4
2  5  6
3  7  8

In [ ]:
import numpy as np
import pandas as pd
ds={ 'EmpNo': pd.Series([1,2,3,4])}
df=pd.DataFrame(ds)
df

   EmpNo
0      1
1      2
2      3
3      4

In [ ]:
class Employee:
  def __init__(self, name, age):
    self.name = name
    self.age = age
  def print(self):
    print("name & age", self.name, self.age)
emp1 = Employee("Monish", 41)
emp1.print()

name & age Monish 41

In [ ]:
class Employee:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def print(self):
        print("Name & Age:", self.name, self.age)

class Department(Employee):
    def __init__(self, name, age, dname, dhead):
        super().__init__(name, age)  # Call the parent class constructor
        self.dhead = dhead  # Initialize the department head attribute
        self.dname=dname
    def print(self):
        super().print()  # Call the parent class's print method
        print("Department Name:", self.dname)
        print("Department Head:", self.dhead)

# Example usage
dept1 = Department( "Monish", 41,"IT","Tom")
dept1.print()

Name & Age: Monish 41
Department Name: IT
Department Head: Tom

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
data = [
    ['USA', 'TX', 25],
    ['USA', 'CA', 15],
    ['USA', 'NY', 10],
    ['AUS', 'NSW', 7],
    ['AUS', 'QLD', 3]
]

# Create the DataFrame
df = pd.DataFrame(data, columns=['Country', 'State', 'Sales'])
#df.groupby(['Country'])['Sales'].sum()
#df.describe()
#df.info()
#df.shape
#df.columns
df.dtypes

Country    object
State      object
Sales       int64
dtype: object

In [ ]:
a={'a','b'}
print(a)
#type(a)
b=set([1,2,3])
print(b)
#type(b)
#print(set([1,2,3]))

a.update(b)
print(a)
b.add(4)
b.add(0)
print(b)
for i in b:
  print(i)

{'b', 'a'}
{1, 2, 3}
{1, 2, 3, 'a', 'b'}
{0, 1, 2, 3, 4}
0
1
2
3
4

In [ ]:
s1='string'
s2=4
try:
  print(s1+s2)
except Exception as e:
  print("error", e)

error can only concatenate str (not "int") to str

In [ ]:
s1='var1'
s2='var2'
try:
  print("%s %s" %(s1,s2))
except Exception as e:
  print("error", e)
except TypeError as e:
  print("error", e)

var1 var2

In [ ]:
s1='Print variables in new format {0}{1}'
s2='new variable1 format'
s3='new variable2 format'
print(s1.format(s2,s3))

Print variables in new format new variable1 formatnew variable2 format

In [ ]:

class bigg():

  def big(self,arr):
      max=arr[0]
      for i in arr:
        if i>max:
          max=i
      return max

arr=[1,2,3]
a=bigg()
print(a.big(arr))

In [ ]:
class big():
  def max(l1,N):
       f_l=[]
       for i in range(0,N):
        max=0
        for j in range(len(l1)):
          if l1[j]>max:
            max=l1[j]
        l1.remove(max)
        f_l.append(max)
       return print(f_l)

  l1=[4,8,5,9]
  N=2
  max(l1,N)

[9, 8]

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df1=pd.read_csv('/emp.csv')
df1.head()

,empid,empname,depid,depname,salary,age,country,city,state,manager_name,manager_ID
0,101,Employee_101,1,Marketing,56630,30,India,Mumbai,ON,Laura Green,202
1,102,Employee_102,1,Marketing,51934,38,UK,Mumbai,NY,Laura Green,208
2,103,Employee_103,3,IT,62224,32,India,Chicago,MH,John Black,205
3,104,Employee_104,2,HR,80982,50,UK,Vancouver,IL,Laura Green,207
4,105,Employee_105,2,HR,71798,57,Canada,Vancouver,MH,Laura Green,205

In [ ]:
df_USA=df1[df1['country']=='USA']
df_USA.shape[0]
#"""COUNT(1) SIMILAR SHAPE[0]"""

16

In [ ]:
df1[df1['country']=='USA'].groupby('state')['salary'].sum()

state
BC    264457
IL    404910
MA     55778
MH    243024
NY    173050
ON    205484
Name: salary, dtype: int64

In [ ]:
df1

,empid,empname,depid,depname,salary,age,country,city,state,manager_name,manager_ID
0,101,Employee_101,1,Marketing,56630,30,India,Mumbai,ON,Laura Green,202
1,102,Employee_102,1,Marketing,51934,38,UK,Mumbai,NY,Laura Green,208
2,103,Employee_103,3,IT,62224,32,India,Chicago,MH,John Black,205
3,104,Employee_104,2,HR,80982,50,UK,Vancouver,IL,Laura Green,207
4,105,Employee_105,2,HR,71798,57,Canada,Vancouver,MH,Laura Green,205
...,...,...,...,...,...,...,...,...,...,...,...
95,196,Employee_196,2,Marketing,105518,42,India,Toronto,BC,Emily White,205
96,197,Employee_197,2,Finance,86265,29,India,New York,MA,Michael Scott,207
97,198,Employee_198,4,HR,55778,41,USA,Chicago,MA,Laura Green,208
98,199,Employee_199,1,Marketing,50464,54,UK,Vancouver,IL,Laura Green,208
99,200,Employee_200,4,HR,93719,41,UK,Vancouver,BC,John Black,204

In [ ]:
import  pandas as pd
df_s=df1.rename(columns={'empname':'Employee Name', 'manger_name':'Manager Name'})
print(df_s)

    empid Employee Name  depid    depname  salary  age country       city  \
31    132  Employee_132      1         HR  119615   37  Canada   New York
75    176  Employee_176      2         HR  119329   44      UK  Vancouver
46    147  Employee_147      3  Marketing  118522   36     USA     London
34    135  Employee_135      3         HR  116562   48  Canada    Toronto
64    165  Employee_165      4    Finance  116307   43      UK   New York
..    ...           ...    ...        ...     ...  ...     ...        ...
1     102  Employee_102      1  Marketing   51934   38      UK     Mumbai
59    160  Employee_160      1    Finance   51220   39   India  Vancouver
76    177  Employee_177      3  Marketing   51025   42      UK     London
98    199  Employee_199      1  Marketing   50464   54      UK  Vancouver
13    114  Employee_114      2         IT   50282   45      UK   New York

   state   manager_name  manager_ID
31    MA     John Black         210
75    BC     John Black         208
46    BC     John Black         207
34    MA    Laura Green         202
64    MA    Emily White         206
..   ...            ...         ...
1     NY    Laura Green         208
59    ON     John Black         208
76    MA     John Black         202
98    IL    Laura Green         208
13    IL  Michael Scott         206

[100 rows x 11 columns]

In [ ]:
df1[['empname', 'salary']]

         empname  salary
0   Employee_101   56630
1   Employee_102   51934
2   Employee_103   62224
3   Employee_104   80982
4   Employee_105   71798
..           ...     ...
95  Employee_196  105518
96  Employee_197   86265
97  Employee_198   55778
98  Employee_199   50464
99  Employee_200   93719

[100 rows x 2 columns]

In [ ]:
df1.columns

Index(['empid', 'empname', 'depid', 'depname', 'salary', 'age', 'country',
       'city', 'state', 'manager_name', 'manager_ID'],
      dtype='object')

In [ ]:
result = df1[['empname','salary']].sort_values(by='salary', ascending=False)

print(result)

         empname  salary
31  Employee_132  119615
75  Employee_176  119329
46  Employee_147  118522
34  Employee_135  116562
64  Employee_165  116307
..           ...     ...
1   Employee_102   51934
59  Employee_160   51220
76  Employee_177   51025
98  Employee_199   50464
13  Employee_114   50282

[100 rows x 2 columns]

In [ ]:
df1 = df1.sort_values(by='salary', ascending=False)
df1['empname'].head(2)

31    Employee_132
75    Employee_176
Name: empname, dtype: object

In [ ]:
df1.groupby('country')['salary'].sum()

country
Canada    2345964
India     2933400
UK        1594232
USA       1346703
Name: salary, dtype: int64

In [ ]:
df6=df1[(df1['country']=='USA') & (df1['state']=='NY')].groupby('depid')['salary'].sum().sort_values(ascending=True)
print(df6)

depid
2    85697
3    87353
Name: salary, dtype: int64

In [ ]:
def greatest(arr):
    max=arr[0]
    for i in arr:
        if i>max:
            max=i
            return max
arr=[1,2,3]
print(greatest(arr))

2

In [ ]:
def arrange(arr):
  return sorted(arr, reverse=True)
arr=[98,2,34]
print(arrange(arr))

[98, 34, 2]

In [ ]:
def arr2(arr):
  first=second=0
  for i in arr:
    if i>first:
      first=i
    elif i>second:
      second=i
  return first,second
arr=[18,25,3]
print(arr2(arr))

(25, 3)

In [ ]:
##dynamically passing values to a function
def config_server(host,port,user,password):
  print(f"server running on : {host},{port}")

server_config={
     'host': '127.0.0.1',
    'port': 8080,
     'user': 'admin',
     'password': 'admin'
}
config_server(**server_config)
#

server running on : 127.0.0.1,8080

In [ ]:
numbers=[8,25,90,56]
##Filter as the name suggests helps to filter your list using filter conditions.
mult5=list(filter(lambda x: x%5==0, numbers))
print(mult5)

[25, 90]

In [ ]:
##The Map function allows us to use a function on a list of elements.
numbers=[87,56,44,24]
def pov(val: int):
  return val**2
print(list(map(pov, numbers)))

[7569, 3136, 1936, 576]

In [ ]:
##The reduce() function is a powerful tool in Python that operates on a list (or any iterable), applies a function to its elements, and ‘reduces’ them to a single output.
from functools import reduce
words=['apple', 'banana', 'cherry', 'date','cherry','apple']
print(reduce(lambda counts, word: {**counts, word: counts.get(word, 0) + 1}, words, {}))

{'apple': 2, 'banana': 1, 'cherry': 2, 'date': 1}

In [ ]:
list = ['a','b','c','d','e']
count = 0
for l in list:
    print('Index:', count,' Value:', l)
    count+=1
##Use Enumerate to achieve the same result:
list = ['a','b','c','d','e']
for count, l in enumerate(list):
    print('Index:', count,' Value:', l)

Index: 0  Value: a
Index: 1  Value: b
Index: 2  Value: c
Index: 3  Value: d
Index: 4  Value: e
Index: 0  Value: a
Index: 1  Value: b
Index: 2  Value: c
Index: 3  Value: d
Index: 4  Value: e

In [ ]:
from collections import Counter

words = ['apple', 'banana', 'cherry', 'date', 'cherry', 'apple']
word_counts = Counter(words)

print(word_counts)

Counter({'apple': 2, 'cherry': 2, 'banana': 1, 'date': 1})

In [ ]:
import pandas as pd

words = ['apple', 'banana', 'cherry', 'date', 'cherry', 'apple']
word_counts = pd.Series(words).value_counts()

print(word_counts)

apple     2
cherry    2
banana    1
date      1
Name: count, dtype: int64

In [ ]:
#Multithreading is a way to achieve parallelism by executing multiple threads of code. A thread is a lightweight process that shares the same memory space as the parent process
import calendar
from concurrent.futures import ThreadPoolExecutor
import requests

def generate_dates(year, month):
    _, last_day = calendar.monthrange(year, month)

    dates = [f"{year}-{month:02d}-{day:02d}" for day in range(1, last_day + 1)]
    return dates

year = 2023
month = 10
result = generate_dates(year, month)
urls = []
for x in result:
    urls.append(f"http://api.nbp.pl/api/exchangerates/rates/a/gbp/{x}/")

def download_page(url):
    response = requests.get(url)
    return response.content

with ThreadPoolExecutor(max_workers=5) as executor:
    results = list(executor.map(download_page, urls))

for result in results:
    print(result)

In [ ]:
##Multiprocessing is a technique used to achieve parallelism by running multiple processes simultaneously. A process is an independent instance of a running program that possesses its own memory space
from multiprocessing import Pool
import time

def square(x):
    time.sleep(1)
    print(x)
    return x * 2


numbers = [1, 2, 3, 4, 5]

if __name__ == '__main__':
    with Pool(processes=2) as pool:
        results = pool.map(square, numbers)
    print(results)

In [ ]:
##adlfs- Azure Account storage integration
import adlfs


fs = adlfs.AzureBlobFileSystem(account_name=os.environ["AZURE_STORAGE_ACCOUNT_NAME"])
local_filename = "landing/clients.csv"

with fs.open(local_filename, "wb") as f:
  f.write("hello;csv;file")

In [ ]:
##s3fs- AWS S3 storage integration
import s3fs

fs = s3fs.S3FileSystem(key=mykey, secret=mysecretkey)
bucket = "my-bucket"


files = fs.ls(bucket)

with s3.open('my-bucket/my-file.txt', 'rb') as f:
  print(f.read())

In [ ]:
##how Pandas can efficiently read large CSV files
import pandas as pd

chunksize = 10 ** 6
for chunk in pd.read_csv(filename, chunksize=chunksize):
    for index, row in chunk.iterrows():
        print(row)

In [ ]:
##SPARK efficiently perform processing tasks on massive datasets while also enabling the distribution of these tasks across multiple computers for enhanced scalability
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago']}


df = spark.createDataFrame(data)
df.printSchema()

In [ ]:
## Polars is a high-performance DataFrame library implemented in Rust and distinguishes itself by prioritizing performance
import polars as pl

# Creating a DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago']}

df = pl.DataFrame(data)
# Filtering data
filtered_df = df.filter(df['Age'] > 30)

# Adding a new column
df = df.with_columns(salary = pl.lit(100))

# Grouping data and calculating statistics
grouped_city = df.groupby('City').agg(pl.col('Age').mean().alias('Avg_Age'))

In [ ]:
##connect to SQL Server
from sqlalchemy import create_engine

# Connection details
server = "your_server_name"  # e.g., "localhost" or "192.168.1.100"
database = "your_database_name"
username = "your_username"
password = "your_password"
driver = "ODBC Driver 17 for SQL Server"  # Verify the driver installed on your system

# Connection string
connection_string = f"mssql+pyodbc://{username}:{password}@{server}/{database}?driver={driver}"

# Create the SQLAlchemy engine
engine = create_engine(connection_string)

# Test the connection
try:
    with engine.connect() as connection:
        print("Connection successful!")
except Exception as e:
    print("Error connecting to the database:", e)

In [3]:
n1=input("enter first number")
n2=input("enter 2nd number")
n3=int(n1)+int(n2)
print("sum of  {0}, {1} is {2}".format(n1,n2,n3))

enter first number3
enter 2nd number4
sum of  3, 4 is 7